#!/bin/bash
SRC_YUV=/Users/omricarmi/Technion/ProjectA/ITUVideos/BasketballDrill_832x480_50.yuv
OUT_BIN=/Users/omricarmi/Technion/ProjectA/outputVideos/test1.bin
CFG_FILE=/Users/omricarmi/Technion/ProjectA/code/FastHEVC/cfg/custom/BasketballDrill_encoder_intra_main.cfg
cmake-build-debug/HM_16_14_ENC -c ${CFG_FILE} -i ${SRC_YUV} -b ${OUT_BIN}
